version: "0.1"
environments:
  - name: main
    branch: main
    mode: pull-request
apps:
  - name: lijialing888.github.io
    path: ""
    text-resources:
      - path: "*.html"
        format: html-hardcoded
